### ISSUE TITLE
super mario maker

### ISSUE THREAD

**Issue by Seil0** [Seil0/cemu_UI#3]
please help me getting all save directory IDs for super mario maker, so i can add them
thanks for your help

currently supported:
* fe31b7f2
* 44fc5929

**Comment by xoko14** [comment]
For me is 44fc5929

**Comment by Seil0** [comment]
Hey @xoko14, thanks for helping me making cemu_UI better. The attached zip file contains a version with the ID added, could you test it and report me back if it's working?
[cemu_UI_testing.zip](https://github.com/Seil0/cemu_UI/files/1250104/cemu_UI_testing.zip)

**Comment by xoko14** [comment]
It's not even launching, I tried unlocking the file from windows. I don't know if I'm doing something wrong.

**Comment by Seil0** [comment]
can you start cemu_UI via cmd with `java -jar cemu_UI.jar` and post the output here?

**Comment by xoko14** [comment]
Here you go:
`ago 25, 2017 4:01:29 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
ADVERTENCIA: unable to change permissions for everybody: C:\Users\Xoko14\.credentials\cemu_UI_credential
ago 25, 2017 4:01:29 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
ADVERTENCIA: unable to change permissions for owner: C:\Users\Xoko14\.credentials\cemu_UI_credential
Directory: true
configfile: true
loading settings... done!
<==========starting loading sql==========>
rom database loaded successfull
games database loaded successfull
loading all rom's on startup to mwc ...
add 17
add 234
add 451
add 668
add 17
add 234
add 451
add 668
add 17
add 234
add 451
add 668
add 17
check if entry removed not done yet!
<==========finished loading sql==========>
sartting cloud initialisation...
selected service is Google Drive
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at cloudControllerInstances.GoogleDriveController.authorize(GoogleDriveController.java:81)
        at cloudControllerInstances.GoogleDriveController.getDriveService(GoogleDriveController.java:100)
        at cloudControllerInstances.GoogleDriveController.main(GoogleDriveController.java:108)
        at application.CloudController.initializeConnection(CloudController.java:36)
        at application.Main.mainWindow(Main.java:129)
        at application.Main.start(Main.java:57)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        ... 1 more
Exception running application application.Main`

**Comment by Seil0** [comment]
Hey I've fixed the issue (hopefully (had a issue with my build setup)),
sorry for this, all should now work as it's used to.
[cemu_testing_031.zip](https://github.com/Seil0/cemu_UI/files/1252535/cemu_testing_031.zip)

**Comment by aurelbdx** [comment]
Thanks. It works with the ID 44fc5929
Can you add screenshots and the possibility to enlarge the window. I have a lot of game.

**Comment by Seil0** [comment]
Currently I'm working a few other things, but ui improvements such as lagrer window (resizable) and completely scalable ui are on my todo list. I implemented the basics for this already. Screenshot are on my list too.
Here you can fnd an overview about all pland tasks:
https://github.com/Seil0/cemu_UI/projects/1

**Comment by xoko14** [comment]
It displayed me the available levels but I'm not able to download them. When I try to download any level it freezes.

**Comment by Seil0** [comment]
I'll take a look at it tomorrow.

**Comment by Seil0** [comment]
Hopefully this is the last testing version.
Issues with smmdb api should be fixed.
[cemu_testing_035.zip](https://github.com/Seil0/cemu_UI/files/1254521/cemu_testing_035.zip)

**Comment by xoko14** [comment]
It seems to work, thanks! 🥇

**Comment by Seil0** [comment]
according to your output you posted earlier, you are using the google drive cloud sync. Can you tell me how's that working?

**Comment by xoko14** [comment]
It's working very well, every time I open the launcher or finish playing a game it syncs. I don't have any issue.
